import { 
  Home, 
  MessageSquare, 
  ShoppingCart, 
  User, 
  Search, 
  Menu, 
  Smartphone, 
  Shirt, 
  Home as HomeIcon, 
  Sparkles, 
  Heart, 
  Star, 
  Headphones, 
  Tag, 
  SquarePen, 
  CheckCircle2, 
  Truck, 
  XCircle, 
  Navigation,
  ArrowRight,
  ChevronRight,
  ChevronLeft,
  Filter,
  ArrowUpRight,
  Plus,
  Minus,
  Wallet,
  Settings,
  HelpCircle,
  LogOut,
  LogIn,
  FileText,
  Package,
  StarHalf,
  Flame,
  Laptop,
  Camera,
  Store,
  ShoppingBasket,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Zap,
  Save,
  ChevronDown,
  History,
  Trash2,
  TrendingUp,
  X,
  Share2,
  ShieldCheck,
  Bell,
  Clock,
  Layout as LayoutIcon,
  Gamepad2,
  Tv,
  Headset,
  Bluetooth,
  Battery,
  Volume2,
  MessageCircle,
  MoreVertical,
  MapPin,
  CreditCard,
  Ticket,
  Lock,
  Edit,
  Award,
  Crown,
  Play,
  Pause,
  RotateCcw,
  RotateCw,
  Check,
  UserCheck,
  Send,
  AlertCircle,
  Image,
  Globe,
  PhoneCall,
  Copy,
  QrCode,
  Eye,
  ExternalLink,
  ShoppingBag
} from 'lucide-react';

export const Icons = {
  Home: (props: any) => <Home {...props} />,
  MessageSquare: (props: any) => <MessageSquare {...props} />,
  ShoppingCart: (props: any) => <ShoppingCart {...props} />,
  User: (props: any) => <User {...props} />,
  Search: (props: any) => <Search {...props} />,
  Menu: (props: any) => <Menu {...props} />,
  Smartphone: (props: any) => <Smartphone {...props} />,
  Shirt: (props: any) => <Shirt {...props} />,
  HomeIcon: (props: any) => <HomeIcon {...props} />,
  Sparkles: (props: any) => <Sparkles {...props} />,
  Heart: (props: any) => <Heart {...props} />,
  Star: (props: any) => <Star {...props} />,
  Headphones: (props: any) => <Headphones {...props} />,
  Tag: (props: any) => <Tag {...props} />,
  SquarePen: (props: any) => <SquarePen {...props} />,
  Truck: (props: any) => <Truck {...props} />,
  XCircle: (props: any) => <XCircle {...props} />,
  Navigation: (props: any) => <Navigation {...props} />,
  ArrowRight: (props: any) => <ArrowRight {...props} />,
  Plus: (props: any) => <Plus {...props} />,
  Minus: (props: any) => <Minus {...props} />,
  Wallet: (props: any) => <Wallet {...props} />,
  Settings: (props: any) => <Settings {...props} />,
  HelpCircle: (props: any) => <HelpCircle {...props} />,
  LogOut: (props: any) => <LogOut {...props} />,
  LogIn: (props: any) => <LogIn {...props} />,
  FileText: (props: any) => <FileText {...props} />,
  Package: (props: any) => <Package {...props} />,
  StarHalf: (props: any) => <StarHalf {...props} />,
  Flame: (props: any) => <Flame {...props} />,
  Laptop: (props: any) => <Laptop {...props} />,
  Camera: (props: any) => <Camera {...props} />,
  Store: (props: any) => <Store {...props} />,
  ShoppingBasket: (props: any) => <ShoppingBasket {...props} />,
  ArrowLeft: (props: any) => <ArrowLeft {...props} />,
  ArrowUp: (props: any) => <ArrowUp {...props} />,
  ArrowDown: (props: any) => <ArrowDown {...props} />,
  Zap: (props: any) => <Zap {...props} />,
  Save: (props: any) => <Save {...props} />,
  ExpandMore: (props: any) => <ChevronDown {...props} />,
  ChevronDown: (props: any) => <ChevronDown {...props} />,
  PhoneCall: (props: any) => <PhoneCall {...props} />,
  History: (props: any) => <History {...props} />,
  Trash2: (props: any) => <Trash2 {...props} />,
  TrendingUp: (props: any) => <TrendingUp {...props} />,
  X: (props: any) => <X {...props} />,
  Share2: (props: any) => <Share2 {...props} />,
  ShieldCheck: (props: any) => <ShieldCheck {...props} />,
  Bell: (props: any) => <Bell {...props} />,
  Clock: (props: any) => <Clock {...props} />,
  Layout: (props: any) => <LayoutIcon {...props} />,
  Gamepad2: (props: any) => <Gamepad2 {...props} />,
  Tv: (props: any) => <Tv {...props} />,
  Headset: (props: any) => <Headset {...props} />,
  Bluetooth: (props: any) => <Bluetooth {...props} />,
  Battery: (props: any) => <Battery {...props} />,
  Noise: (props: any) => <Volume2 {...props} />,
  MessageCircle: (props: any) => <MessageCircle {...props} />,
  More: (props: any) => <MoreVertical {...props} />,
  MapPin: (props: any) => <MapPin {...props} />,
  CreditCard: (props: any) => <CreditCard {...props} />,
  CheckCircle2: (props: any) => <CheckCircle2 {...props} />,
  ChevronRight: (props: any) => <ChevronRight {...props} />,
  Ticket: (props: any) => <Ticket {...props} />,
  Lock: (props: any) => <Lock {...props} />,
  Edit: (props: any) => <Edit {...props} />,
  Award: (props: any) => <Award {...props} />,
  Crown: (props: any) => <Crown {...props} />,
  Play: (props: any) => <Play {...props} />,
  Pause: (props: any) => <Pause {...props} />,
  RotateCcw: (props: any) => <RotateCcw {...props} />,
  RotateCw: (props: any) => <RotateCw {...props} />,
  ChevronLeft: (props: any) => <ChevronLeft {...props} />,
  Filter: (props: any) => <Filter {...props} />,
  ArrowUpRight: (props: any) => <ArrowUpRight {...props} />,
  Check: (props: any) => <Check {...props} />,
  UserCheck: (props: any) => <UserCheck {...props} />,
  Send: (props: any) => <Send {...props} />,
  AlertCircle: (props: any) => <AlertCircle {...props} />,
  Image: (props: any) => <Image {...props} />,
  Globe: (props: any) => <Globe {...props} />,
  Copy: (props: any) => <Copy {...props} />,
  QrCode: (props: any) => <QrCode {...props} />,
  Eye: (props: any) => <Eye {...props} />,
  ExternalLink: (props: any) => <ExternalLink {...props} />,
  ShoppingBag: (props: any) => <ShoppingBag {...props} />
};

